{"name": "# Verify phone \"310.817.0370\" is here", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\003_main_page_phone_here.py\", line 8, in vrf_phn_here\n    context.app.main_page.vrf_phn_here(phone)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\autocareparts_gene_kayakov\\pages\\main_page.py\", line 53, in vrf_phn_here\n    actual_text = wait.until(EC.visibility_of_element_located((PHONE_IS_HERE))).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1612062234364, "stop": 1612062235391}, {"name": "Then Verify phone \"310.817.0370\" is here", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\003_main_page_phone_here.py\", line 8, in vrf_phn_here\n    context.app.main_page.vrf_phn_here(phone)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\autocareparts_gene_kayakov\\pages\\main_page.py\", line 53, in vrf_phn_here\n    actual_text = wait.until(EC.visibility_of_element_located((PHONE_IS_HERE))).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1612062235391, "stop": 1612062258528}], "start": 1612062229106, "stop": 1612062260671, "uuid": "ed427006-cdd4-4487-b022-64be1efcd728", "historyId": "13811a0c003581d411a5a230904ac2b3", "fullName": "features/tests/003_main_page_phone_here.feature:# Verify phone \"310.817.0370\" is here", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# Verify phone \"310.817.0370\" is here"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}